#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-theme-bootstrap
PKG_VERSION:=2022
PKG_RELEASE:=1

PKG_LICENSE:=GPLv3
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=hugo9966

include $(INCLUDE_DIR)/package.mk

define Package/$(PKG_NAME)
  CATEGORY:=hugo9966
  SUBMENU:=theme
  TITLE:=theme
  URL:=https://github.com/esirplayground/LingTiGameAcc
endef

define Package/$(PKG_NAME)/description
a theme for luci interface
endef
